Source/MvcWithLogin/Controllers/PersonController.cs
using Domain.Commands;
using Domain.Entities;
using Domain.Interfaces;
using Domain.Queries;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PersonController : Controller
    {
        private readonly IQueryHandler<PersonListQuery, Task<Person[]>> queryHandler;
        private readonly IQueryHandler<PersonSingleQuery, Task<Person>> querySingleHandler;
        private readonly IQueryHandler<PersonFindSingleQuery, Task<Person>> queryFindSingleHandler;
        private readonly ICommandHandler<CreatePerson> createCommandHandler;
        private readonly ICommandHandler<EditPerson> editCommandHandler;
        private readonly ICommandHandler<DeletePerson> deleteCommandHandler;

        public PersonController(
            IQueryHandler<PersonListQuery, Task<Person[]>> queryHandler,
            IQueryHandler<PersonSingleQuery, Task<Person>> querySingleHandler,
            IQueryHandler<PersonFindSingleQuery, Task<Person>> queryFindSingleHandler,
            ICommandHandler<CreatePerson> createCommandHandler,
            ICommandHandler<EditPerson> editCommandHandler,
            ICommandHandler<DeletePerson> deleteCommandHandler
            )
        {
            this.queryHandler = queryHandler ??
                throw new ArgumentNullException(nameof(queryHandler));
            this.querySingleHandler = querySingleHandler ??
                throw new ArgumentNullException(nameof(querySingleHandler));
            this.queryFindSingleHandler = queryFindSingleHandler ??
                throw new ArgumentNullException(nameof(queryFindSingleHandler));
            this.editCommandHandler = editCommandHandler
                ?? throw new ArgumentNullException(nameof(editCommandHandler));
            this.deleteCommandHandler = deleteCommandHandler ??
                throw new ArgumentNullException(nameof(deleteCommandHandler));
            this.createCommandHandler = createCommandHandler ??
                throw new ArgumentNullException(nameof(createCommandHandler));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewData["ShowRecords"] = 15;
            var persons = await queryHandler.Handle(new PersonListQuery());
            return View(persons);
        }

        [HttpGet("IndexShowAll")]
        public async Task<IActionResult> IndexShowAll()
        {
            ViewData["ShowRecords"] = 100000;
            var persons = await queryHandler.Handle(new PersonListQuery());
            return View("Index", persons);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string cprNumber)
        {
            //todo add text onbad input and person not found
            if (string.IsNullOrEmpty(cprNumber) || cprNumber.Length < 10)
            {
                return View("Index", new Person[0]);
            }

            var person = await queryFindSingleHandler.Handle(new PersonFindSingleQuery { CprNumber = cprNumber });

            if (person == null)
            {
                return View("Index", new Person[0]);
            }
            else
            {
                return View("Details", person);
            }
        }        

        [HttpPost("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync([FromForm] EditPerson person)
        {
            if (person.Id == null)
            {
                return BadRequest();
            }

            await editCommandHandler.Handle(person);

            //TODO, reset field not working 
            person.NewTestResult.Result = null;

            return View(person);
        }

        [HttpGet("Edit")]
        public async Task<IActionResult> EditAsync(string id, string birthday)
        {
            if (id == null)
            {
                return BadRequest();
            }

            //TODO handle cpr/birthday change
            var person = await querySingleHandler.Handle(new PersonSingleQuery { Id = id, Birthday = birthday });

            if (person == null)
            {
                return NotFound();
            }

            //TODO use automapper 
            var editPerson = new EditPerson { Id = person.Id, FirstName = person.FirstName, LastName = person.LastName, CprNo = person.CprNo, TestResults = person.TestResults };
            editPerson.NewTestResult = new TestResult { TestDate = DateTime.Now };

            return View(editPerson);
        }

        [HttpGet("Details")]
        public async Task<IActionResult> DetailsAsync(string id, string birthday)
        {
            var person = await querySingleHandler.Handle(new PersonSingleQuery { Id = id, Birthday = birthday });

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        [HttpGet("Create")]
        public IActionResult CreateAsync()
        {
            var person = new CreatePerson();
            return View(person);
        }

        [HttpPost("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync([FromForm] CreatePerson person)
        {
            await createCommandHandler.Handle(person);
            return View(person);
        }

        [HttpGet("Delete")]
        public async Task<IActionResult> DeleteAsync(string id, string birthday)
        {
            var person = await querySingleHandler.Handle(new PersonSingleQuery { Id = id, Birthday = birthday});
            return View(person);
        }

        [HttpGet("DoDelete")]        
        public async Task<IActionResult> DoDeleteAsync(string id, string birthday)
        {
            await deleteCommandHandler.Handle(new DeletePerson { Id = id, Birthday = birthday});
            return RedirectToAction("Index");
        }
    }
}

Source/MvcWithLogin/Views/Person/Create.cshtml
@model Domain.Commands.CreatePerson

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Create Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CprNo" class="control-label"></label>
                <input asp-for="CprNo" class="form-control" />
                <span asp-validation-for="CprNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/MvcWithLogin/Views/Person/Delete.cshtml
@model Domain.Entities.Person

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CprNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CprNo)
        </dd>
    </dl>

    @if (Model.TestResults != null && Model.TestResults.Count() > 0)
    {
        <h4>Test resultater</h4>
        @for (int i = 0; i < Model.TestResults.Count(); i++)
        {
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => Model.TestResults[i].TestDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => Model.TestResults[i].TestDate)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => Model.TestResults[i].Result)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => Model.TestResults[i].Result)
                </dd>
            </dl>
        }
    }
    else
    {
        <h4>Ingen test resultater</h4>
    }
</div>
<div>
    <a asp-action="DoDelete" asp-route-id="@Model.Id" asp-route-birthday="@Model.Birthday">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

Source/MvcWithLogin/Views/Person/Details.cshtml
@model Domain.Entities.Person

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detaljer</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CprNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CprNo)
        </dd>
    </dl>

    @if (Model.TestResults != null && Model.TestResults.Count() > 0)
    {
        <h4>Test resultater</h4>
        @for (int i = 0; i < Model.TestResults.Count(); i++)
        {
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => Model.TestResults[i].TestDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => Model.TestResults[i].TestDate)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => Model.TestResults[i].Result)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => Model.TestResults[i].Result)
                </dd>
            </dl>
        }
    }
    else
    {
        <h4>Ingen test resultater</h4>
    }


</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" asp-route-birthday="@Model.Birthday">Edit</a> |
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id, birth }) |*@
    <a asp-action="Index">Back to List</a>
</div>

Source/MvcWithLogin/Views/Person/Edit.cshtml
@model Domain.Commands.EditPerson

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Edit Person</h4>
<hr />

<form asp-action="Edit">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control hide" />
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CprNo" class="control-label"></label>
                <input asp-for="CprNo" class="form-control" />
                <span asp-validation-for="CprNo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>

        <div class="col-md-8 border">
            <div class="container">
                <h4>Tilføj nyt testresult</h4>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewTestResult.TestDate, new { @class = "control-label" })
                    @Html.EditorFor(Model => Model.NewTestResult.TestDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(Model => Model.NewTestResult.TestDate)
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.NewTestResult.Result, new { @class = "control-label" })
                    @Html.EditorFor(Model => Model.NewTestResult.Result, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(Model => Model.NewTestResult.Result)
                </div>
            </div>
            <div class="container">
                @if (Model.NumberOfTestResults == 0)
                {
                    <h4>Ingen tidligere test resultater</h4>
                }
                else
                {
                    <h4>Test resultater</h4>
                }

                @for (int i = 0; i < Model.NumberOfTestResults; i++)
                {
                    <div class="form-group">
                        @Html.LabelFor(Model => Model.TestResults[i].TestDate, new { @class = "control-label" })
                        @Html.EditorFor(Model => Model.TestResults[i].TestDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(Model => Model.TestResults[i].TestDate)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(Model => Model.TestResults[i].Result, new { @class = "control-label" })
                        @Html.EditorFor(Model => Model.TestResults[i].Result, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(Model => Model.TestResults[i].Result)
                    </div>
                }
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/MvcWithLogin/Views/Person/Index.cshtml
@model IEnumerable<Domain.Entities.Person>

@{
    ViewData["Title"] = "Index";    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a> |
    <a asp-action="IndexShowAll" title="Test performance for mange records">Vis alle resultater</a>
</p>
<div>
    <form class="search-form" asp-controller="Person" asp-action="Index">
        <p>
            Find person
            <input type="text" id="cprNumber" class="form-control" placeholder="Skriv cpr nummer her" name="cprNumber" />
            <input type="submit" value="Find" class="btn btn-primary" /> | 
            <a asp-action="Index">Tilbage til listen</a>
        </p>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birthday)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Take((int)ViewData["ShowRecords"]))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" asp-route-birthday="@item.Birthday">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" asp-route-birthday="@item.Birthday">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" asp-route-birthday="@item.Birthday">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>